### PR TITLE
Adding key to push return results

### PR DESCRIPTION
**Pull request by matthewdaniel**
This pull request is to add the key to the result of pushing data into firebase. Thus when the success handler is called you can use the key to redirect the user or whatever else you need.

### CODE REVIEW

**Comment by deg** [comment]
I won't have time to look at this carefully for a day or two. But, some quick questions:
1) Can you add a few lines of comments and/or docs explaining this.
2) Will these changes cause any potential breaks to existing users? Consider that the passed in on-success can be either a function or an event vector
3) [It's been a while since I looked at Firebase, so I don't remember...] 
   a) Can separating the push and the set break any atomicity guarantees?
   b) Firebase will be forcing a move soon to their new API. Will this create any problems for that port?

**Comment by matthewdaniel** [comment]
No worries. I'm doing proof on concept and I have your project now in lein checkouts.
1. do you mean update the readme.md or in code comments or comments here?
2. since it was previously calling success without any value i would be surprised if it broke things but I'm no clojure expert here. I have tested it with on-success as a handler and as on success being an fn that accepts a param and a fn without any parameters. 
3. 
a) no, keys are always unique so once you generate a key. I'm pretty sure it doesn't even go over the wire to generate the key. Also, this is the current officially recommended way on their guides. https://firebase.google.com/docs/database/web/read-and-write#updating_or_deleting_data
b.) As noted in 'a' this approach is in their current official documentation.

**Comment by deg** [comment]
Thanks!  This all sounds good. I'll want to test on my apps too but, based on what you say, I don't expect any surprises.

Re readme.md: Probably all that is needed is a a few lines of comments in the code.  (I just took a quick look at my current text, and I don't think it has enough depth to justify explaining this there. Of course, if you want to, more docs are always good!)

**Comment by matthewdaniel** [comment]
I've updated your read.me with an example

**Comment by deg** [comment]
Thanks!!

I'd like to merge this soon, but I'm slammed with other work this week.  I'll try to test and accept next week.

I hope you are ok for now with lein checkouts?

**Comment by matthewdaniel** [comment]
Yes, i'm in no hurry.

**Comment by deg** [comment]
Thanks. Merged.

**Pull request merged**
