### PR TITLE
Phone authentication

### PR DESCRIPTION
**Pull request by shen-tian**
As promised. Almost got all of #4 done.

A few things to note:

- I'm using the `firebase-state` atom in `core` to store the reCaptcha states. Feels more appropriate than using a global var. Hope that's OK?
- I didn't implement all the optional bells and whistles for this auth flow. (mostly to do with re-Captcha stuff). I'd rather leave that until someone want to use those.

### CODE REVIEW

**Comment by deg** [comment]
Thank you for doing this!  (and sorry for my delay in answering; still catching up after a great vacation).

Thank you for pointing out that you are using `firebase-state` in a slightly new way. I agree that this is better than introducing a new global.

But. perhaps, it would be better not to require an explicit event to initialize the captcha. Might it be cleaner to do this via an additional keyword parameter to `set-firebase-state`? That would let users' code be a bit more compact, and would make the use of `firebase-state` feel more natural.

Re the optional bells and whistles - I agree: better to wait until someone really needs them so they get battle-tested when written.

**Comment by shen-tian** [comment]
Just saw the comments now. No worries.

I'm not too familiar with how captcha works, but as far as I can tell, it's attached to the DOM element that is used to trigger the "send SMS" event, to stop the mechanism from being used to send spam SMS's. Thus, it can only be initiated once the element is rendered, and not, in a general use case, on app init (where we do the firebase init).

We can certainly build a reagent component that combines the initialising of reCaptcha and dispatching of phone auth flow. But that would probably overstep the scope of this library, I think.

**Comment by deg** [comment]
Hmm, I'm not sure if you misunderstood me or, at least as likely, I misunderstood what your code is doing.

What I meant to say was:

You commented "I'm using the firebase-state atom in core to store the reCaptcha states. Feels more appropriate than using a global var.".

I agree that is appropriate to use this existing atom.

But, it feels wrong to init the state in two places, so I was suggesting a merge of your function `init-recaptcha` into `set-firebase-state` by adding more keyword parameters.

I was not suggesting adding more recaptcha logic into the library. I agree with you that doing so would be overstepping scope.

**Comment by shen-tian** [comment]
Hmm.. let me check if I understand. Right now, we have this:

```clj
(defn init-recaptcha [{:keys [on-solve container-id]}]
  (let [recaptcha (js/firebase.auth.RecaptchaVerifier.
                   container-id
                   (clj->js {:size     "invisible"
                             :callback #(re-frame/dispatch on-solve)}))]
    (swap! core/firebase-state assoc
           :recaptcha-verifier recaptcha)))
```

Are you suggesting 

1. Instead of calling the `swap!` on `core/firebase-state`, we use an updated version of `set-firebase-state` instead? OR
2. `init-recaptcha` should be called when `core/init` is run? 

The first one, can definitely do, the second will be challenging, as `container-id` is typically not available when an app first starts. Thus any more automatic calling of `init-recaptcha` will have to do with hooking into React lifecycle fn's, rather than global Firebase init.

**Comment by deg** [comment]
I was suggesting your second option. But, looks like I was wrong. I had not realized that `container-id` was not available early enough.  So, I retract my suggestion.

As for your first option, I don't know. It appeals to me a bit, since it seems to localize access to the atom, even though it doesn't add that much readability to what you've already done.

Maybe the right answer is a lightweight helper function, something like:

```
(def set-firebase-state (partial apply swap! core/firebase-state assoc))

(defn set-firebase-state [& {:keys [get-user-sub set-user-event default-error-handler]}]
  (set-firebase-state
         {:set-user-fn           (event->fn set-user-event)
         :get-user-fn           (sub->fn get-user-sub)
         :default-error-handler (event->fn (or default-error-handler js/alert)})))

,,,

(defn init-recaptcha [{:keys [on-solve container-id]}]
  (let ,,,
    (set-firebase-state {:recaptcha-verifier recaptcha})))
```

But I'm writing this late at night and am not totally convinced this is much better than what you already have. (Also, ignore any typos I may have made).

**Comment by shen-tian** [comment]
@deg : have a look at this version? I played around with a few versions of generalised `set-firebase-state`, and didn't come up with anything too satisfactory. So I settled on something a bit verbose but at least simple. On the one hand, allowing a general "assoc into the global state" felt a bit pointless. On the other hand, using the same giant `set-firebase-state` fn would make it quite complicated, as it would need to be called on app init, but also later, during auth flow. (e.g. if we omit `default-error-handler` on app start, it means we should set it to the default `js/alert`. But if we omit it later on, the correct behaviour is probably to leave the existing one in place etc.)

In the end the setup as it stands now at least:

- Centralises access to the atom
- Make it quite clear what it's doing, without complicating what's already there.
- [Downside] a bit more code than before.

I'm not sure this is better than the last version either. But don't feel the choice is critical at this stage :)

**Comment by deg** [comment]
I prefer your original version.  (Sorry to have run you around like this!)
I'm ready to accept the PR.

I don't know the mechanics of how to accept just one commit from a PR. Can you save me a few minutes, and revert the last commit?  (Fine just to commit a reversing one; I'll squash them all together).

**Comment by shen-tian** [comment]
No worries! Reverted last commit.

**Comment by deg** [comment]
Thanks!

**Pull request merged**
