### PR TITLE
Support for Facebook, Twitter and Github Auth providers

### PR DESCRIPTION
**Pull request by pbzdyl**
Hello @deg!

I have added support for other OAuth providers.

Any comments are welcome! :)

Best regards,
Piotr

### CODE REVIEW

**Comment by deg** [comment]
Thanks, this looks great. I am away for a few days, but will aim to review carefully on Sunday or Monday.

**Comment by deg** [comment]
This is a great addition, thanks!

Can you add a bit more to make it even better:
1.  Catch exceptions and direct them to `core/default-error-handler`. For example, I was able to trigger uncaught exceptions `auth/operation-not-allowed` by using a provider I had not setup and `auth/account-exists-with-different-credential` by logging in as the same user from two providers.
2. Adjust variable names in `is-user-equal` and `onSignIn` to not look limited to Google.
3. Add a few lines of documentation pointing to the Firebase docs that explain how to configure auth. (I think this is mostly in https://firebase.google.com/docs/auth/). Ideally, also add links or tips about how to configure authentication in dev vs production environments, since many users of this library will be new to all this.

Thanks!

**Comment by pbzdyl** [comment]
Thank you for your feedback @deg.

I have added error handling around sign-in method call as you suggested and added a bit about additional options supported for sign-in and enabling/configuring sign-in method in Firebase console.

However, I am not sure how I could adjust `is-user-equal` and `onSignIn` functions implementation as I don't know how they are used - I couldn't find any usage of this function in the repository. Those functions also assume that Google provider is used - I am not sure how could I determine which actual provider should be used there if Google one shouldn't be hardcoded.

Do you have any suggestions how this code should be adjusted?

Thank you!

**Comment by deg** [comment]
Your changes look good.

Re `onSignIn` - that came from the original code I had copied to write this library. I had assumed that it was a required callback in the authentication handshake. But, I just checked a bit more carefully and:
1. The code does not appear to be called (though I want to double-check after I've had a night's sleep).
2. It is documented in https://firebase.google.com/docs/auth/web/google-signin as being part of the manual sign in flow, which we are not currently using and which I don't yet fully understand.

So, I think it is safe to leave this as is, and for me to eventually delete it once I've tested a bit more.
Sorry for the false alarm.

I did notice one other problem now. The github flow seems to work with `:sign-in-method :popup`, but not with `:redirect`. In the latter case, the login attempt just silently fails.

Do you have time to look into this a little bit deeper?  I'd be satisfied with any of the following:
1. Each of the providers working with both :redirect and :popup
2. Any case that doesn't work giving a runtime error; either by catching the failure or even by just having the code check explicitly for cases that don't work.
3. Simply adding documentation saying which cases work.

Do you have the time and scaffolding to test all the cases? I've already verified that google works both with :redirect and :popup and that github only with :popup in the current code. I've not tested any of the other combinations.

**Comment by pbzdyl** [comment]
I won't have time to implement an automated test for this but I have a template app that allows using all 4 supported auth providers in both modes where I was able to confirm they all work with both redirect as well as popup methods: https://proto-app.bzdyl.net/

It also uses error handling added in one of the commits - e.g. when you choose Google login with popup and close the sign in window before confirming sign in - there will be a notification message displayed which is triggered by [`default-error-handler`](https://github.com/deg/re-frame-firebase/pull/1/files#diff-6384630ee1f94b25e02d5b82a88bab09R66).

**Comment by deg** [comment]
Can you share the source code for your proto-app?  In my code, `{:firebase/github-sign-in {:sign-in-method :redirect}}` does not work. I assume I'm doing something wrong, but not sure what (and we should document the failure path to help the next folks to try this).

**Comment by deg** [comment]
I pinned down the problem.  My code only fails if I've already created a user with the same email via Google.  In :popup mode, my error handler gets called, but in :redirect mode, it fails silently.

**Comment by pbzdyl** [comment]
Of course, the source code is [hosted on BitBucket](https://bitbucket.org/badyl/proto).

**Comment by deg** [comment]
I think the same problem exists in your app too:
- Delete your user from the firebase app
- Login with github
- Logout
- Login with Github, redirect.  You will see no error, but not be logged in.

**Comment by pbzdyl** [comment]
Hmm, that's strange as there is no error reported, even in the console. I wonder if the same issue exists for a pure JS applications.

**Comment by deg** [comment]
It would be great if you see a way to fix this. But, it is an edge case, and this PR adds enough value as is. I am fine accepting the PR with just a warning in the docs. We can then open an issue to fix this later.

**Comment by deg** [comment]
Actually, the open edge case is part of a bigger issue of linking multiple auth providers.
Not a huge issue, but too big for right now. I'm going to accept this PR as is, and just open an issue for the remaining parts.

**Comment by pbzdyl** [comment]
Thank you for taking time to review this!

**Pull request merged**
