### PR TITLE
Improve firestore example and its documentation

### LINKED ISSUE #21: Firestore demo docs
Hi,

I have tried to run the firestore example, and it does work, but only a few little fixes. Probably just needs to be mentioned in the docs.

1. remove -SNAPSHOT from the dependency (new to clojure, is it a known issue / optimization?)
2. add the firestore.api-keys namespace, or include it in some other way. Obviously you can't commit your credentials here, but a dummy file would be appreciated. Especially since the firestore init is different from the firebase init used in the main docs (needs projectId)
3. you probably need to run the firebase init command at some point to make it work. It's documented on the firebase side, but a little mention wouldn't hurt :)

thanks!

### PR DESCRIPTION
**Pull request by gabrielsimoes**
Closes #21

### CODE REVIEW

**Review by deg — COMMENTED** [review]
Thanks for combining the two :requires.
While you are touching this, can you also put them libraries in some order?  I like either:
- Completely alphabetical; or
- Clojure and clojure libraries first, followed by 3rd-party packages, followed by other libraries I've written, followed by other namespaces in this application

**Review by deg — COMMENTED** [review]
I'm being _really_ pedantic here (sorry!). But, as long as I'm asking you to make other changes, please also change on line 20: "on step 1" should be "in step 1"

**Review by deg — APPROVED** [review]

**Review by deg — APPROVED** [review]

**Review by deg — APPROVED** [review]

**Review by deg — APPROVED** [review]

**Comment by deg** [comment]
Thanks.  This looks great.  I commented a few tiny suggestions. If you have time, please make those changes.

**Comment by gabrielsimoes** [comment]
Sure, somehow I wasn't notified by github, but I'll get this done soon.

**Comment by gabrielsimoes** [comment]
OK, I think I made all the changes. Please tell me if there is anything else to be done.

**Comment by deg** [comment]
Wow, sorry. Just discovered that I missed this.

**Review by deg — APPROVED** [review]

**Pull request merged**
