### PR TITLE
Add support to Firestore

### PR DESCRIPTION
**Pull request by gabrielsimoes**
It is still a WIP, but I'm creating a PR since you might be interested in the chnges I have already made.

I refactored the namespaces without modifying the public API. Take a look if you  like the way I changed things. I think it might be necessary to modify some more things, since the effects `:firebase/write`, `:firebase:push` and `:firebase/read-once` will be a little misleading/conflicting with firestore.

### CODE REVIEW

**Comment by deg** [comment]
Thanks!

The dependency changes look fine.

I don't have time right now to look carefully at the refactoring changes. I'll try to get to this soon.
Meanwhile, please look at the changes in PR #14, still pending, to verify that you've not done anything incompatible.

**Comment by gabrielsimoes** [comment]
My refactoring is only a namespace one, moving and renaming things around. It shouldn't conflict with anything. I'd just have to apply the same refactoring to the changes made in PR #14.

**Comment by deg** [comment]
Thanks.  I basically like what you've done. I also like that you've separated these noisy refactorings from the "real" work of supporting Firestore.

That said, some comments:

- Your dependency updates are good. But, some of the libraries have changed since last week, so I updated all but one dependency in a separate commit that I've just pushed.  I did not update Firebase itself; I'd rather that happens as part of the real Firestore PR, when someone can give it real testing.

- It looks like the rest of your changes were to separate the database functions from the core namespace. I mostly like what you did. But, I think the real problem is that I had effectively created two core namespaces:  `com.degel.re-frame-firebase` and `com.degel.re-frame-firebase.core`. I think that the best fix is for core.cljs to disappear entirely.  The functions that you left there should move up to re_frame_firebase.cljs. The rest of the file should be divided into separate files like you did here. core.cljs itself should be deleted.

**Comment by gabrielsimoes** [comment]
I agree with you. I only think it would be best to eventually delete `re-frame-firebase` instead of `re-frame-firebase.core`. It would cause a serious api change, of course, but then we would be following a more standard namespace separation (it is the same `re-frame` and `reagent` use, for example).

**Comment by deg** [comment]
I'm mixed on that.  I used to prefer using core.cljs, but I've recently seen a few projects that use this style -- keeping the externally useful functions one level up, so I decided to try it for this project.  I find a bit more awkward when writing, but I think it slightly helps reading the code.

In any event, like you said, changing this would break the API, so it's not going to happen

**Comment by gabrielsimoes** [comment]
Alright, I have implemented all the functionalities, except for transactions. I didn't come up with a good idea for them. I have added a example app which I used to test (you can use it, so you don't have to implement firestore in your projects just to test). Take a look and then I'll write the documentation and solve conflicts.

**Comment by deg** [comment]
Thank you!

It will be a few days before I have time to look at it, so just wanted to let you know that I see it's here and will get back to you soon.

**Comment by gabrielsimoes** [comment]
Sorry, I found some things I have/want to change while writing the documentation. Give me a day and I'll push the changes.

**Comment by gabrielsimoes** [comment]
Alright, I have changed the things I wanted to change and documented everything. I ended up making a little mess with the commits. I hope you don't mind for now. When everything is ready to be merged I can reorganize them.

**Comment by deg** [comment]
Looks like I'll finally have some time to look at this, today or tomorrow.
Do you have any more changes you want to make first?

**Comment by gabrielsimoes** [comment]
No, you can take a look.

**Comment by deg** [comment]
Damn, I missed the window again. I will try to get to this real soon.  By early next week, I hope.

**Comment by deg** [comment]
Very nice work. Thank you!

**Comment by gabrielsimoes** [comment]
Thanks! #10 and #13 can be closed now.

**Pull request merged**
