### PR TITLE
Allow passing Firestore settings

### PR DESCRIPTION
**Pull request by smogg**
Right now the app will display the following warning when Firestore is used:

screen shot 2018-08-13 at 18 26 38

This PR introduces another key to the `firebase/init` function where one can pass the requested [Firestore setting](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings):

```clojure
(firebase/init :firebase-app-info  firebase-app-info
               :firestore-settings {:timestampsInSnapshots true}
               :get-user-sub       [:user]
               :set-user-event     [:set-user])
```

In addition to that, I've also cleaned up the Firestore example a little bit.

### CODE REVIEW

**Review by deg — COMMENTED** [review]
This PR looks good. Thanks!
I do have a few requests:
- Please squash your entire change into one commit.  That makes it easier for me to review in Github's online tools.
- Have the firestore sample project depend on a non-snapshot version of this (so 0.7.0, not 0.8.0-SNAPSHOT). The original use of 0.6.0-SNAPSHOT was a mistake that I had failed to catch at the time).

I'll continue this comment in response to each of your commits, in a moment.

**Review by deg — COMMENTED** [review]
(continuing from my review comment of your previous commit)

- Please add a brief source comment, linking to the explanation of why `:timestampsInSnapshots` is needed.
- Does Firestore properly handle the case of `firestore-settings` being nil? If not, please add some bulletproofing here.

**Review by deg — COMMENTED** [review]
(continuing...)

... Ah, you read my mind :-) and addressed the last comment in my previous message.  Just one tweak here: I'd move the check down into `set-firestore-settings`. That should make the code a bit more robust.

**Review by deg — COMMENTED** [review]
(continuing)

- This code in the readme can also use a comment linking to why :timestampsInSnapshots is needed

**Comment by deg** [comment]
Oh, damn!  Github made me review each of your commits individually, but then put a "View changes" by each one showing the collective changes.  Gag me!

Please read them with the understanding that each of my four review comments referred to one of your commits, in order.

**Comment by smogg** [comment]
@deg thanks for the review. The PR now includes one commit, and I've addressed your comments.

**Review by deg — APPROVED** [review]

**Pull request merged**
